/**
 * Laser Platform
 * The user-end API for using Laser, the function-as-a-service.
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { FunctionBundle } from '../model/functionBundle';
import { InlineResponse200 } from '../model/inlineResponse200';
import { InlineResponse2001 } from '../model/inlineResponse2001';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class FunctionBundleService {

    protected basePath = 'https://virtserver.swaggerhub.com/gjz0107/laser-platform/1.0.0';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Add a function bundle.
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public addFunctionBundle(body?: FunctionBundle, observe?: 'body', reportProgress?: boolean): Observable<FunctionBundle>;
    public addFunctionBundle(body?: FunctionBundle, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<FunctionBundle>>;
    public addFunctionBundle(body?: FunctionBundle, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<FunctionBundle>>;
    public addFunctionBundle(body?: FunctionBundle, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // authentication (bearerAuth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<FunctionBundle>(`${this.basePath}/function_bundles`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete the bundle.
     * Delete the bundle.
     * @param bundleId The id of the function bundle.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteFunctionBundle(bundleId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteFunctionBundle(bundleId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteFunctionBundle(bundleId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteFunctionBundle(bundleId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (bundleId === null || bundleId === undefined) {
            throw new Error('Required parameter bundleId was null or undefined when calling deleteFunctionBundle.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearerAuth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/function_bundles/${encodeURIComponent(String(bundleId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the download link for the function bundle.
     * Get the download link about the function bundle.
     * @param bundleId The id of the function bundle.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public downloadFunctionBundle(bundleId: string, observe?: 'body', reportProgress?: boolean): Observable<InlineResponse200>;
    public downloadFunctionBundle(bundleId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<InlineResponse200>>;
    public downloadFunctionBundle(bundleId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<InlineResponse200>>;
    public downloadFunctionBundle(bundleId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (bundleId === null || bundleId === undefined) {
            throw new Error('Required parameter bundleId was null or undefined when calling downloadFunctionBundle.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearerAuth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<InlineResponse200>(`${this.basePath}/function_bundles/${encodeURIComponent(String(bundleId))}/bundle`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Flush all running instances of this function bundle.
     * Flush all running instances of this function bundle.
     * @param bundleId The id of the function bundle.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public flushFunctionBundleInstances(bundleId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public flushFunctionBundleInstances(bundleId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public flushFunctionBundleInstances(bundleId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public flushFunctionBundleInstances(bundleId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (bundleId === null || bundleId === undefined) {
            throw new Error('Required parameter bundleId was null or undefined when calling flushFunctionBundleInstances.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearerAuth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/function_bundles/${encodeURIComponent(String(bundleId))}/instances`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get information about the function bundle.
     * Get information about the function bundle.
     * @param bundleId The id of the function bundle.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFunctionBundle(bundleId: string, observe?: 'body', reportProgress?: boolean): Observable<FunctionBundle>;
    public getFunctionBundle(bundleId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<FunctionBundle>>;
    public getFunctionBundle(bundleId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<FunctionBundle>>;
    public getFunctionBundle(bundleId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (bundleId === null || bundleId === undefined) {
            throw new Error('Required parameter bundleId was null or undefined when calling getFunctionBundle.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearerAuth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<FunctionBundle>(`${this.basePath}/function_bundles/${encodeURIComponent(String(bundleId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Modify the function bundle.
     * 
     * @param bundleId The id of the function bundle.
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public putFunctionBundle(bundleId: string, body?: FunctionBundle, observe?: 'body', reportProgress?: boolean): Observable<FunctionBundle>;
    public putFunctionBundle(bundleId: string, body?: FunctionBundle, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<FunctionBundle>>;
    public putFunctionBundle(bundleId: string, body?: FunctionBundle, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<FunctionBundle>>;
    public putFunctionBundle(bundleId: string, body?: FunctionBundle, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (bundleId === null || bundleId === undefined) {
            throw new Error('Required parameter bundleId was null or undefined when calling putFunctionBundle.');
        }


        let headers = this.defaultHeaders;

        // authentication (bearerAuth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<FunctionBundle>(`${this.basePath}/function_bundles/${encodeURIComponent(String(bundleId))}`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the upload link for the function bundle.
     * Get the upload link about the function bundle.
     * @param bundleId The id of the function bundle.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public uploadFunctionBundle(bundleId: string, observe?: 'body', reportProgress?: boolean): Observable<InlineResponse2001>;
    public uploadFunctionBundle(bundleId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<InlineResponse2001>>;
    public uploadFunctionBundle(bundleId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<InlineResponse2001>>;
    public uploadFunctionBundle(bundleId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (bundleId === null || bundleId === undefined) {
            throw new Error('Required parameter bundleId was null or undefined when calling uploadFunctionBundle.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearerAuth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.put<InlineResponse2001>(`${this.basePath}/function_bundles/${encodeURIComponent(String(bundleId))}/bundle`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
