/**
 * Laser Platform
 * The user-end API for using Laser, the function-as-a-service.
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface API { 
    id: string;
    name: string;
    /**
     * OpenAPI specification with Laser metadata for the API.
     */
    spec?: string;
}